"""add contact inquiries

Revision ID: 291b9552d692
Revises: e518f89e76f5
Create Date: 2026-07-28 10:08:12.558789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "291b9552d692"
down_revision: Union[str, Sequence[str], None] = "e518f89e76f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_inquiries",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("company", sa.String(length=150), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "inquiry_type",
            sa.String(length=30),
            server_default=sa.text("'general'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default=sa.text("'new'"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.String(length=20),
            server_default=sa.text("'normal'"),
            nullable=False,
        ),
        sa.Column(
            "is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_to_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column(
            "consent_given",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("source_page", sa.String(length=2048), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address_hash", sa.String(length=64), nullable=True),
        sa.Column("submission_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "inquiry_type IN ('general', 'employment', 'freelance', 'contract', 'collaboration', 'project', 'support', 'other')",
            name=op.f("ck_contact_inquiries_contact_inquiries_type_allowed"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high', 'urgent')",
            name=op.f("ck_contact_inquiries_contact_inquiries_priority_allowed"),
        ),
        sa.CheckConstraint(
            "status <> 'closed' OR closed_at IS NOT NULL",
            name=op.f(
                "ck_contact_inquiries_contact_inquiries_closed_requires_timestamp"
            ),
        ),
        sa.CheckConstraint(
            "status <> 'responded' OR responded_at IS NOT NULL",
            name=op.f(
                "ck_contact_inquiries_contact_inquiries_responded_requires_timestamp"
            ),
        ),
        sa.CheckConstraint(
            "status IN ('new', 'in_progress', 'responded', 'closed', 'spam')",
            name=op.f("ck_contact_inquiries_contact_inquiries_status_allowed"),
        ),
        sa.CheckConstraint(
            "(is_read = false AND read_at IS NULL) OR (is_read = true AND read_at IS NOT NULL)",
            name=op.f("ck_contact_inquiries_contact_inquiries_read_state_consistent"),
        ),
        sa.CheckConstraint(
            "company IS NULL OR length(btrim(company)) > 0",
            name=op.f("ck_contact_inquiries_contact_inquiries_company_not_blank"),
        ),
        sa.CheckConstraint(
            "internal_notes IS NULL OR length(btrim(internal_notes)) > 0",
            name=op.f(
                "ck_contact_inquiries_contact_inquiries_internal_notes_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "ip_address_hash IS NULL OR length(ip_address_hash) = 64",
            name=op.f("ck_contact_inquiries_contact_inquiries_ip_hash_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(email::text)) >= 3",
            name=op.f("ck_contact_inquiries_contact_inquiries_email_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(message)) >= 10",
            name=op.f("ck_contact_inquiries_contact_inquiries_message_min_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(name)) >= 2",
            name=op.f("ck_contact_inquiries_contact_inquiries_name_min_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(subject)) >= 3",
            name=op.f("ck_contact_inquiries_contact_inquiries_subject_min_length"),
        ),
        sa.CheckConstraint(
            "phone IS NULL OR length(btrim(phone)) > 0",
            name=op.f("ck_contact_inquiries_contact_inquiries_phone_not_blank"),
        ),
        sa.CheckConstraint(
            "source_page IS NULL OR length(btrim(source_page)) > 0",
            name=op.f("ck_contact_inquiries_contact_inquiries_source_page_not_blank"),
        ),
        sa.CheckConstraint(
            "submission_fingerprint IS NULL OR length(submission_fingerprint) = 64",
            name=op.f("ck_contact_inquiries_contact_inquiries_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "user_agent IS NULL OR length(btrim(user_agent)) > 0",
            name=op.f("ck_contact_inquiries_contact_inquiries_user_agent_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
            name=op.f("fk_contact_inquiries_assigned_to_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_contact_inquiries_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_inquiries")),
    )
    op.create_index(
        "ix_contact_inquiries_admin_listing",
        "contact_inquiries",
        ["status", "priority", "is_read", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_contact_inquiries_assigned_to_id"),
        "contact_inquiries",
        ["assigned_to_id"],
        unique=False,
    )
    op.create_index(
        "ix_contact_inquiries_assignment_listing",
        "contact_inquiries",
        ["assigned_to_id", "status", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_contact_inquiries_deleted_at"),
        "contact_inquiries",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_email"), "contact_inquiries", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_contact_inquiries_inquiry_type"),
        "contact_inquiries",
        ["inquiry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_ip_address_hash"),
        "contact_inquiries",
        ["ip_address_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_is_read"),
        "contact_inquiries",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_priority"),
        "contact_inquiries",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_project_id"),
        "contact_inquiries",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_contact_inquiries_project_listing",
        "contact_inquiries",
        ["project_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_contact_inquiries_sender_listing",
        "contact_inquiries",
        ["email", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_contact_inquiries_status"),
        "contact_inquiries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_submission_fingerprint"),
        "contact_inquiries",
        ["submission_fingerprint"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_contact_inquiries_submission_fingerprint"),
        table_name="contact_inquiries",
    )
    op.drop_index(op.f("ix_contact_inquiries_status"), table_name="contact_inquiries")
    op.drop_index(
        "ix_contact_inquiries_sender_listing",
        table_name="contact_inquiries",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_contact_inquiries_project_listing",
        table_name="contact_inquiries",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_contact_inquiries_project_id"), table_name="contact_inquiries"
    )
    op.drop_index(op.f("ix_contact_inquiries_priority"), table_name="contact_inquiries")
    op.drop_index(op.f("ix_contact_inquiries_is_read"), table_name="contact_inquiries")
    op.drop_index(
        op.f("ix_contact_inquiries_ip_address_hash"), table_name="contact_inquiries"
    )
    op.drop_index(
        op.f("ix_contact_inquiries_inquiry_type"), table_name="contact_inquiries"
    )
    op.drop_index(op.f("ix_contact_inquiries_email"), table_name="contact_inquiries")
    op.drop_index(
        op.f("ix_contact_inquiries_deleted_at"), table_name="contact_inquiries"
    )
    op.drop_index(
        "ix_contact_inquiries_assignment_listing",
        table_name="contact_inquiries",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_contact_inquiries_assigned_to_id"), table_name="contact_inquiries"
    )
    op.drop_index(
        "ix_contact_inquiries_admin_listing",
        table_name="contact_inquiries",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("contact_inquiries")
    # ### end Alembic commands ###
