"""add portfolio project domain

Revision ID: e518f89e76f5
Revises: fc710990420c
Create Date: 2026-07-21 19:02:08.391573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e518f89e76f5"
down_revision: Union[str, Sequence[str], None] = "fc710990420c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_categories",
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("seo_title", sa.String(length=70), nullable=True),
        sa.Column("seo_description", sa.String(length=170), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'",
            name=op.f("ck_project_categories_project_categories_color_hex_format"),
        ),
        sa.CheckConstraint(
            "description IS NULL OR length(btrim(description)) > 0",
            name=op.f("ck_project_categories_project_categories_description_not_blank"),
        ),
        sa.CheckConstraint(
            "icon IS NULL OR length(btrim(icon)) > 0",
            name=op.f("ck_project_categories_project_categories_icon_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(name::text)) >= 2",
            name=op.f("ck_project_categories_project_categories_name_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(slug::text)) >= 2",
            name=op.f("ck_project_categories_project_categories_slug_not_blank"),
        ),
        sa.CheckConstraint(
            "seo_description IS NULL OR length(btrim(seo_description)) > 0",
            name=op.f(
                "ck_project_categories_project_categories_seo_description_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "seo_title IS NULL OR length(btrim(seo_title)) > 0",
            name=op.f("ck_project_categories_project_categories_seo_title_not_blank"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f(
                "ck_project_categories_project_categories_sort_order_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_categories")),
    )
    op.create_index(
        op.f("ix_project_categories_deleted_at"),
        "project_categories",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_categories_is_active"),
        "project_categories",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_categories_name"), "project_categories", ["name"], unique=True
    )
    op.create_index(
        "ix_project_categories_public_listing",
        "project_categories",
        ["is_active", "sort_order", "name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_project_categories_slug"), "project_categories", ["slug"], unique=True
    )
    op.create_table(
        "project_technologies",
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.String(length=30),
            server_default=sa.text("'other'"),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("official_url", sa.String(length=2048), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('language','framework','library','database','platform','cloud','devops','testing','tool','service','other')",
            name=op.f("ck_project_technologies_project_technologies_category_allowed"),
        ),
        sa.CheckConstraint(
            "color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'",
            name=op.f("ck_project_technologies_project_technologies_color_hex_format"),
        ),
        sa.CheckConstraint(
            "description IS NULL OR length(btrim(description)) > 0",
            name=op.f(
                "ck_project_technologies_project_technologies_description_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "icon IS NULL OR length(btrim(icon)) > 0",
            name=op.f("ck_project_technologies_project_technologies_icon_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(name::text)) >= 2",
            name=op.f("ck_project_technologies_project_technologies_name_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(slug::text)) >= 2",
            name=op.f("ck_project_technologies_project_technologies_slug_not_blank"),
        ),
        sa.CheckConstraint(
            "official_url IS NULL OR length(btrim(official_url)) > 0",
            name=op.f(
                "ck_project_technologies_project_technologies_official_url_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f(
                "ck_project_technologies_project_technologies_sort_order_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_technologies")),
    )
    op.create_index(
        op.f("ix_project_technologies_category"),
        "project_technologies",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_technologies_deleted_at"),
        "project_technologies",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_technologies_is_active"),
        "project_technologies",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_technologies_name"),
        "project_technologies",
        ["name"],
        unique=True,
    )
    op.create_index(
        "ix_project_technologies_public_listing",
        "project_technologies",
        ["category", "sort_order", "name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.create_index(
        op.f("ix_project_technologies_slug"),
        "project_technologies",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "projects",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=True),
        sa.Column("solution_summary", sa.Text(), nullable=True),
        sa.Column("key_features", sa.Text(), nullable=True),
        sa.Column("technical_highlights", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.String(length=20),
            server_default=sa.text("'private'"),
            nullable=False,
        ),
        sa.Column(
            "is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("repository_url", sa.String(length=2048), nullable=True),
        sa.Column("live_url", sa.String(length=2048), nullable=True),
        sa.Column("case_study_url", sa.String(length=2048), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("seo_title", sa.String(length=70), nullable=True),
        sa.Column("seo_description", sa.String(length=170), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_projects_projects_published_requires_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_projects_projects_status_allowed"),
        ),
        sa.CheckConstraint(
            "visibility IN ('public', 'private', 'unlisted')",
            name=op.f("ck_projects_projects_visibility_allowed"),
        ),
        sa.CheckConstraint(
            "case_study_url IS NULL OR length(btrim(case_study_url)) > 0",
            name=op.f("ck_projects_projects_case_study_url_not_blank"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_projects_projects_completion_not_before_start"),
        ),
        sa.CheckConstraint(
            "key_features IS NULL OR length(btrim(key_features)) > 0",
            name=op.f("ck_projects_projects_key_features_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(description)) >= 20",
            name=op.f("ck_projects_projects_description_min_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(short_description)) >= 10",
            name=op.f("ck_projects_projects_short_description_min_length"),
        ),
        sa.CheckConstraint(
            "length(btrim(slug::text)) >= 2",
            name=op.f("ck_projects_projects_slug_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(title)) >= 2",
            name=op.f("ck_projects_projects_title_not_blank"),
        ),
        sa.CheckConstraint(
            "live_url IS NULL OR length(btrim(live_url)) > 0",
            name=op.f("ck_projects_projects_live_url_not_blank"),
        ),
        sa.CheckConstraint(
            "problem_statement IS NULL OR length(btrim(problem_statement)) > 0",
            name=op.f("ck_projects_projects_problem_statement_not_blank"),
        ),
        sa.CheckConstraint(
            "repository_url IS NULL OR length(btrim(repository_url)) > 0",
            name=op.f("ck_projects_projects_repository_url_not_blank"),
        ),
        sa.CheckConstraint(
            "seo_description IS NULL OR length(btrim(seo_description)) > 0",
            name=op.f("ck_projects_projects_seo_description_not_blank"),
        ),
        sa.CheckConstraint(
            "seo_title IS NULL OR length(btrim(seo_title)) > 0",
            name=op.f("ck_projects_projects_seo_title_not_blank"),
        ),
        sa.CheckConstraint(
            "solution_summary IS NULL OR length(btrim(solution_summary)) > 0",
            name=op.f("ck_projects_projects_solution_summary_not_blank"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_projects_projects_sort_order_non_negative")
        ),
        sa.CheckConstraint(
            "technical_highlights IS NULL OR length(btrim(technical_highlights)) > 0",
            name=op.f("ck_projects_projects_technical_highlights_not_blank"),
        ),
        sa.CheckConstraint(
            "thumbnail_url IS NULL OR length(btrim(thumbnail_url)) > 0",
            name=op.f("ck_projects_projects_thumbnail_url_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["project_categories.id"],
            name=op.f("fk_projects_category_id_project_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_projects_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_projects_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        "ix_projects_admin_listing",
        "projects",
        ["status", "visibility", "is_featured", "sort_order", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_projects_category_id"), "projects", ["category_id"], unique=False
    )
    op.create_index(
        "ix_projects_category_listing",
        "projects",
        ["category_id", "status", "sort_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_projects_created_by_id"), "projects", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_projects_is_featured"), "projects", ["is_featured"], unique=False
    )
    op.create_index(
        "ix_projects_public_listing",
        "projects",
        ["is_featured", "sort_order", "published_at"],
        unique=False,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status = 'published' AND visibility = 'public' AND published_at IS NOT NULL"
        ),
    )
    op.create_index(
        op.f("ix_projects_published_at"), "projects", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(
        op.f("ix_projects_updated_by_id"), "projects", ["updated_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_visibility"), "projects", ["visibility"], unique=False
    )
    op.create_table(
        "project_links",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "link_type",
            sa.String(length=30),
            server_default=sa.text("'other'"),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column(
            "opens_in_new_tab",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "link_type IN ('repository', 'live_demo', 'documentation', 'case_study', 'video', 'download', 'app_store', 'play_store', 'design', 'article', 'api', 'other')",
            name=op.f("ck_project_links_project_links_type_allowed"),
        ),
        sa.CheckConstraint(
            "icon IS NULL OR length(btrim(icon)) > 0",
            name=op.f("ck_project_links_project_links_icon_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(label)) >= 2",
            name=op.f("ck_project_links_project_links_label_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(url)) > 0",
            name=op.f("ck_project_links_project_links_url_not_blank"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f("ck_project_links_project_links_sort_order_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_links_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_links")),
    )
    op.create_index(
        op.f("ix_project_links_deleted_at"),
        "project_links",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_links_is_active"), "project_links", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_project_links_link_type"), "project_links", ["link_type"], unique=False
    )
    op.create_index(
        op.f("ix_project_links_project_id"),
        "project_links",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_links_project_listing",
        "project_links",
        ["project_id", "is_active", "sort_order", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_project_links_public_listing",
        "project_links",
        ["project_id", "sort_order"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.create_index(
        "uq_project_links_active_project_url",
        "project_links",
        ["project_id", "url"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "project_media",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "media_type",
            sa.String(length=20),
            server_default=sa.text("'image'"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("provider_asset_id", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "media_type IN ('image', 'video', 'document', 'demo', 'other')",
            name=op.f("ck_project_media_project_media_type_allowed"),
        ),
        sa.CheckConstraint(
            "alt_text IS NULL OR length(btrim(alt_text)) > 0",
            name=op.f("ck_project_media_project_media_alt_text_not_blank"),
        ),
        sa.CheckConstraint(
            "caption IS NULL OR length(btrim(caption)) > 0",
            name=op.f("ck_project_media_project_media_caption_not_blank"),
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds > 0",
            name=op.f("ck_project_media_project_media_duration_positive"),
        ),
        sa.CheckConstraint(
            "file_size_bytes IS NULL OR file_size_bytes > 0",
            name=op.f("ck_project_media_project_media_file_size_positive"),
        ),
        sa.CheckConstraint(
            "height IS NULL OR height > 0",
            name=op.f("ck_project_media_project_media_height_positive"),
        ),
        sa.CheckConstraint(
            "length(btrim(url)) > 0",
            name=op.f("ck_project_media_project_media_url_not_blank"),
        ),
        sa.CheckConstraint(
            "mime_type IS NULL OR length(btrim(mime_type)) > 0",
            name=op.f("ck_project_media_project_media_mime_type_not_blank"),
        ),
        sa.CheckConstraint(
            "provider IS NULL OR length(btrim(provider)) > 0",
            name=op.f("ck_project_media_project_media_provider_not_blank"),
        ),
        sa.CheckConstraint(
            "provider_asset_id IS NULL OR length(btrim(provider_asset_id)) > 0",
            name=op.f("ck_project_media_project_media_provider_asset_id_not_blank"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f("ck_project_media_project_media_sort_order_non_negative"),
        ),
        sa.CheckConstraint(
            "thumbnail_url IS NULL OR length(btrim(thumbnail_url)) > 0",
            name=op.f("ck_project_media_project_media_thumbnail_url_not_blank"),
        ),
        sa.CheckConstraint(
            "width IS NULL OR width > 0",
            name=op.f("ck_project_media_project_media_width_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_media_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_media")),
    )
    op.create_index(
        op.f("ix_project_media_deleted_at"),
        "project_media",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_media_is_primary"),
        "project_media",
        ["is_primary"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_media_media_type"),
        "project_media",
        ["media_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_media_project_id"),
        "project_media",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_media_project_listing",
        "project_media",
        ["project_id", "sort_order", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_project_media_provider_asset",
        "project_media",
        ["provider", "provider_asset_id"],
        unique=False,
        postgresql_where=sa.text(
            "provider IS NOT NULL AND provider_asset_id IS NOT NULL"
        ),
    )
    op.create_index(
        "uq_project_media_primary_per_project",
        "project_media",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = true AND deleted_at IS NULL"),
    )
    op.create_table(
        "project_technology_associations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("technology_id", sa.Uuid(), nullable=False),
        sa.Column(
            "is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f(
                "ck_project_technology_associations_project_technology_associations_sort_order_non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_technology_associations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["project_technologies.id"],
            name=op.f(
                "fk_project_technology_associations_technology_id_project_technologies"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_technology_associations")),
    )
    op.create_index(
        op.f("ix_project_technology_associations_deleted_at"),
        "project_technology_associations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_technology_associations_is_featured"),
        "project_technology_associations",
        ["is_featured"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_technology_associations_project_id"),
        "project_technology_associations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_technology_associations_project_listing",
        "project_technology_associations",
        ["project_id", "is_featured", "sort_order", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_project_technology_associations_technology_id"),
        "project_technology_associations",
        ["technology_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_technology_associations_technology_listing",
        "project_technology_associations",
        ["technology_id", "project_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_project_technology_associations_active_pair",
        "project_technology_associations",
        ["project_id", "technology_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_project_technology_associations_active_pair",
        table_name="project_technology_associations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_project_technology_associations_technology_listing",
        table_name="project_technology_associations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_project_technology_associations_technology_id"),
        table_name="project_technology_associations",
    )
    op.drop_index(
        "ix_project_technology_associations_project_listing",
        table_name="project_technology_associations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_project_technology_associations_project_id"),
        table_name="project_technology_associations",
    )
    op.drop_index(
        op.f("ix_project_technology_associations_is_featured"),
        table_name="project_technology_associations",
    )
    op.drop_index(
        op.f("ix_project_technology_associations_deleted_at"),
        table_name="project_technology_associations",
    )
    op.drop_table("project_technology_associations")
    op.drop_index(
        "uq_project_media_primary_per_project",
        table_name="project_media",
        postgresql_where=sa.text("is_primary = true AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_project_media_provider_asset",
        table_name="project_media",
        postgresql_where=sa.text(
            "provider IS NOT NULL AND provider_asset_id IS NOT NULL"
        ),
    )
    op.drop_index(
        "ix_project_media_project_listing",
        table_name="project_media",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_project_media_project_id"), table_name="project_media")
    op.drop_index(op.f("ix_project_media_media_type"), table_name="project_media")
    op.drop_index(op.f("ix_project_media_is_primary"), table_name="project_media")
    op.drop_index(op.f("ix_project_media_deleted_at"), table_name="project_media")
    op.drop_table("project_media")
    op.drop_index(
        "uq_project_links_active_project_url",
        table_name="project_links",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_project_links_public_listing",
        table_name="project_links",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.drop_index(
        "ix_project_links_project_listing",
        table_name="project_links",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_project_links_project_id"), table_name="project_links")
    op.drop_index(op.f("ix_project_links_link_type"), table_name="project_links")
    op.drop_index(op.f("ix_project_links_is_active"), table_name="project_links")
    op.drop_index(op.f("ix_project_links_deleted_at"), table_name="project_links")
    op.drop_table("project_links")
    op.drop_index(op.f("ix_projects_visibility"), table_name="projects")
    op.drop_index(op.f("ix_projects_updated_by_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_published_at"), table_name="projects")
    op.drop_index(
        "ix_projects_public_listing",
        table_name="projects",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status = 'published' AND visibility = 'public' AND published_at IS NOT NULL"
        ),
    )
    op.drop_index(op.f("ix_projects_is_featured"), table_name="projects")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_by_id"), table_name="projects")
    op.drop_index(
        "ix_projects_category_listing",
        table_name="projects",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_projects_category_id"), table_name="projects")
    op.drop_index(
        "ix_projects_admin_listing",
        table_name="projects",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("projects")
    op.drop_index(
        op.f("ix_project_technologies_slug"), table_name="project_technologies"
    )
    op.drop_index(
        "ix_project_technologies_public_listing",
        table_name="project_technologies",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active = true"),
    )
    op.drop_index(
        op.f("ix_project_technologies_name"), table_name="project_technologies"
    )
    op.drop_index(
        op.f("ix_project_technologies_is_active"), table_name="project_technologies"
    )
    op.drop_index(
        op.f("ix_project_technologies_deleted_at"), table_name="project_technologies"
    )
    op.drop_index(
        op.f("ix_project_technologies_category"), table_name="project_technologies"
    )
    op.drop_table("project_technologies")
    op.drop_index(op.f("ix_project_categories_slug"), table_name="project_categories")
    op.drop_index(
        "ix_project_categories_public_listing",
        table_name="project_categories",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_project_categories_name"), table_name="project_categories")
    op.drop_index(
        op.f("ix_project_categories_is_active"), table_name="project_categories"
    )
    op.drop_index(
        op.f("ix_project_categories_deleted_at"), table_name="project_categories"
    )
    op.drop_table("project_categories")
    # ### end Alembic commands ###
